<template>
<div class="container animatedd fadeInn fastt">
    <div class="row">
        <div class="col-md-12">
        <h4>Aviso legal</h4>

        <p>
            PROMOCIÓN MÁS MEGAS POR 3 MESES
        TOTALPLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. PROMOCIÓN VÁLIDA DEL 1 AL 31 DE MARZO DEL 2021. PROMOCIÓN DISPONIBLE APLICA PARA CLIENTES NUEVOS EN LA CONTRATACIÓN DE TOTALPLAY TV + INTERNET / TOTALPLAY TV + INTERNET + NETFLIX / TOTALPLAY TV + INTERNET + AMAZON PRIME . EL PAQUETE INICIAL RECIBIRÁ 30 MEGAS DE DESCARGA DURANTE 30 DÍAS. EL PAQUETE DIVIÉRTETE RECIBIRÁ 80 MEGAS DE DESCARGA DURANTE 3 MESES. EL PAQUETE DIVIÉRTETE+ RECIBIRÁ 200 MEGAS DE DESCARGA DURANTE 3 MESES. EL PAQUETE EMOCIÓNATE RECIBIRÁ 400 MEGAS DE DESCARGA DURANTE 3. AL FINALIZAR LOS MESES DE PROMOCIÓN SE REGRESARÁ A LA VELOCIDAD DE DESCARGA DEL PAQUETE CONTRATADO.

        </p>

        <h4>DESCUENTO DE POR VIDA</h4>

        <p>
        TOTALPLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. PROMOCIONES VÁLIDAS DEL 1 AL 31 DE MARZO DEL 2021. TOTALPLAY TV + INTERNET. DESCUENTO DE POR VIDA: LOS PRIMEROS 5 MESES SE PAGARÁ: PAQUETE INICIAL $619 PRONTO PAGO Y $669 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $669 PRONTO PAGO Y $719 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $769 PRONTO PAGO Y $819 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,199 PRONTO PAGO Y $1,279 PRECIO DE LISTA, SORPRÉNDETE $1,779 PRONTO PAGO Y $1,859 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $849 PRONTO PAGO Y $899 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $949 PRONTO PAGO Y $999 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,379 PRONTO PAGO Y $1,459 PRECIO DE LISTA, SORPRÉNDETE $1,959 PRONTO PAGO Y $2,039 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $909 PRONTO PAGO Y $959 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $1,009 PRONTO PAGO Y $1,059 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,439 PRONTO PAGO Y $1,519 PRECIO DE LISTA, SORPRÉNDETE $2,019 PRONTO PAGO Y $2,000 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $759 PRONTO PAGO Y $809 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $859 PRONTO PAGO Y $909 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,289 PRONTO PAGO Y $1,369 PRECIO DE LISTA, SORPRÉNDETE $1,869 PRONTO PAGO Y $1,949 PRECIO DE LISTA.
        A PARTIR DEL SEXTO MES SE APLICARÁN DE MANERA MENSUAL LOS SIGUIENTES DESCUENTOS TOTALPLAY TV + INTERNET: PAQUETE INICIAL $40 PESOS, PAGANDO $579 PRONTO PAGO Y $629 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $629 PRONTO PAGO Y $679 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $699 PRONTO PAGO Y $749 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,119 PRONTO PAGO Y $1,199 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,679 PRONTO PAGO Y $1,759 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $809 PRONTO PAGO Y $859 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $879 PRONTO PAGO Y $929 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,299 PRONTO PAGO Y $1,379 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,859 PRONTO PAGO Y $1,759 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $869 PRONTO PAGO Y $919 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $939 PRONTO PAGO Y $989 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,359 PRONTO PAGO Y $1,439 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,919 PRONTO PAGO Y $1,999 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $719 PRONTO PAGO Y $769 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $789 PRONTO PAGO Y $839 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,209 PRONTO PAGO Y $1,289 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,769 PRONTO PAGO Y $1,849 PRECIO DE LISTA.
        TOTALPLAY INTERNET. DESCUENTO DE POR VIDA: LOS PRIMEROS 5 MESES SE PAGARÁ: PAQUETE INICIAL $509 PRONTO PAGO Y $459 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $529 PRONTO PAGO Y $579 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $629 PRONTO PAGO Y $679 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $999 PRONTO PAGO Y $1,079 PRECIO DE LISTA, SORPRÉNDETE $1,579 PRONTO PAGO Y $1,659 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $709 PRONTO PAGO Y $759 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $809 PRONTO PAGO Y $859 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,179 PRONTO PAGO Y $1,259 PRECIO DE LISTA, SORPRÉNDETE $1,759 PRONTO PAGO Y $1,839 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $769 PRONTO PAGO Y $819 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $869 PRONTO PAGO Y $919 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,239 PRONTO PAGO Y $1,319 PRECIO DE LISTA, SORPRÉNDETE $1,819 PRONTO PAGO Y $1,899 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $619 PRONTO PAGO Y $669 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $719 PRONTO PAGO Y $769 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,089 PRONTO PAGO Y $1,169 PRECIO DE LISTA, SORPRÉNDETE $1,669 PRONTO PAGO Y $1,749 PRECIO DE LISTA. A PARTIR DEL SEXTO MES SE APLICARÁN DE MANERA MENSUAL LOS SIGUIENTES DESCUENTOS TOTALPLAY INTERNET: PAQUETE INICIAL $20 PESOS, PAGANDO $439 PRONTO PAGO Y $489 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $509 PRONTO PAGO Y $559 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $599 PRONTO PAGO Y $649 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $949 PRONTO PAGO Y $1,029 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,499 PRONTO PAGO Y $1,579 PRECIO DE LISTA. TOTALPLAY INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $689 PRONTO PAGO Y $739 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $779 PRONTO PAGO Y $829 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $1,129 PRONTO PAGO Y $1,209 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,679 PRONTO PAGO Y $1,759 PRECIO DE LISTA. TOTALPLAY INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $749 PRONTO PAGO Y $799 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $839 PRONTO PAGO Y $889 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $1,189 PRONTO PAGO Y $1,209 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,739 PRONTO PAGO Y $1,819 PRECIO DE LISTA. TOTALPLAY INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $599 PRONTO PAGO Y $649 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $689 PRONTO PAGO Y $739 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $1,039 PRONTO PAGO Y $1,119 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,589 PRONTO PAGO Y $1,669 PRECIO DE LISTA.
        </p>

        <h4>
        EN CIUDADES FRONTERIZAS:
        </h4>

        <p>
        TOTALPLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. APLICA PARA LAS NUEVAS CONTRATACIONES DE TOTALPLAY INTERNET + TV EN LAS ZONAS CON COBERTURA TOTALPLAY EN LAS CIUDADES DE TIJUANA Y CD. JUÁREZ DESCUENTO DE POR VIDA: TOTAL PLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. PROMOCIONES VÁLIDAS DEL 1 AL 31 DE MARZO DEL 2021. TOTALPLAY TV + INTERNET. DESCUENTO DE POR VIDA: LOS PRIMEROS 5 MESES SE PAGARÁ: PAQUETE INICIAL $577 PRONTO PAGO Y $623 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $623 PRONTO PAGO Y $670 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $716 PRONTO PAGO Y $763 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,117 PRONTO PAGO Y $1,191 PRECIO DE LISTA, SORPRÉNDETE $1,657 PRONTO PAGO Y $1,731 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $791 PRONTO PAGO Y $837 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $884 PRONTO PAGO Y $931 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,284 PRONTO PAGO Y $1,359 PRECIO DE LISTA, SORPRÉNDETE $1,824 PRONTO PAGO Y $1,899 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $847 PRONTO PAGO Y $893 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $940 PRONTO PAGO Y $986 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,340 PRONTO PAGO Y $1,415 PRECIO DE LISTA, SORPRÉNDETE $1,880 PRONTO PAGO Y $1,955 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $707 PRONTO PAGO Y $754 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $800 PRONTO PAGO Y $847 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,201 PRONTO PAGO Y $1,275 PRECIO DE LISTA, SORPRÉNDETE $1,741 PRONTO PAGO Y $1,815 PRECIO DE LISTA.
        A PARTIR DEL SEXTO MES SE APLICARÁN DE MANERA MENSUAL LOS SIGUIENTES DESCUENTOS TOTALPLAY TV + INTERNET: PAQUETE INICIAL $40 PESOS, PAGANDO $537 PRONTO PAGO Y $583 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $583 PRONTO PAGO Y $630 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $646 PRONTO PAGO Y $693 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,037 PRONTO PAGO Y $1,111 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,557 PRONTO PAGO Y $1,631 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $751 PRONTO PAGO Y $797 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $814 PRONTO PAGO Y $861 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,204 PRONTO PAGO Y $1,279 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,724 PRONTO PAGO Y $1,799 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $807 PRONTO PAGO Y $853 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $870 PRONTO PAGO Y $916 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,260 PRONTO PAGO Y $1,335 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,780 PRONTO PAGO Y $1,815 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $40 PESOS, PAGANDO $667 PRONTO PAGO Y $714 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $70 PESOS, PAGANDO $730 PRONTO PAGO Y $777 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $80 PESOS, PAGANDO $1,121 PRONTO PAGO Y $1,195 PRECIO DE LISTA, SORPRÉNDETE $100 PESOS, PAGANDO $1,641 PRONTO PAGO Y $1,715 PRECIO DE LISTA.
        TOTALPLAY INTERNET. DESCUENTO DE POR VIDA: LOS PRIMEROS 5 MESES SE PAGARÁ: PAQUETE INICIAL $428 PRONTO PAGO Y $474 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $493 PRONTO PAGO Y $540 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $586 PRONTO PAGO Y $633 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $931 PRONTO PAGO Y $1,005 PRECIO DE LISTA, SORPRÉNDETE $1,471 PRONTO PAGO Y $1,545 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $661 PRONTO PAGO Y $707 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $754 PRONTO PAGO Y $800 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,098 PRONTO PAGO Y $1,173 PRECIO DE LISTA, SORPRÉNDETE $1,638 PRONTO PAGO Y $1,713 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $716 PRONTO PAGO Y $763 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $810 PRONTO PAGO Y $856 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,154 PRONTO PAGO Y $1,229 PRECIO DE LISTA, SORPRÉNDETE $1,694 PRONTO PAGO Y $1,769 PRECIO DE LISTA. TOTALPLAY TV + INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $577 PRONTO PAGO Y $623 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $670 PRONTO PAGO Y $716 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $1,014 PRONTO PAGO Y $1,089 PRECIO DE LISTA, SORPRÉNDETE $1,554 PRONTO PAGO Y $1,629 PRECIO DE LISTA. A PARTIR DEL SEXTO MES SE APLICARÁN DE MANERA MENSUAL LOS SIGUIENTES DESCUENTOS TOTALPLAY INTERNET: PAQUETE INICIAL $20 PESOS, PAGANDO $408 PRONTO PAGO Y $454 PRECIO DE LISTA, PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $473 PRONTO PAGO Y $520 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $556 PRONTO PAGO Y $603 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $881 PRONTO PAGO Y $955 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,391 PRONTO PAGO Y $1,465 PRECIO DE LISTA. TOTALPLAY INTERNET + NETFLIX 2 HD. PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $641 PRONTO PAGO Y $687 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $724 PRONTO PAGO Y $770 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $1,048 PRONTO PAGO Y $1,123 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,558 PRONTO PAGO Y $1,633 PRECIO DE LISTA. TOTALPLAY INTERNET + NETFLIX 4 UHD. PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $696 PRONTO PAGO Y $743 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $780 PRONTO PAGO Y $826 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $1,104 PRONTO PAGO Y $1,179 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,614 PRONTO PAGO Y $1,689 PRECIO DE LISTA. TOTALPLAY INTERNET + AMAZON PRIME. PAQUETE DIVIÉRTETE $20 PESOS, PAGANDO $557 PRONTO PAGO Y $603 PRECIO DE LISTA, PAQUETE DIVIÉRTETE+ $30 PESOS, PAGANDO $640 PRONTO PAGO Y $686 PRECIO DE LISTA, PAQUETE EMOCIÓNATE $50 PESOS, PAGANDO $964 PRONTO PAGO Y $1,039 PRECIO DE LISTA, SORPRÉNDETE $80 PESOS, PAGANDO $1,474 PRONTO PAGO Y $1,549 PRECIO DE LISTA.
        </p>

        <h4>
        BONO AL PORTAR LA LÍNEA TELEFÓNICA
        </h4>

        <p>
        TOTALPLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. PROMOCIÓN VÁLIDA DEL 1 AL 31 DE MARZO DEL 2021. PROMOCIÓN DISPONIBLE PARA CLIENTES NUEVOS, AL CONTRATAR TOTALPLAY INTERNET + TV Y PORTAR LA LÍNEA TELEFÓNICA A TOTALPLAY. A PARTIR DE QUE SE REALICE LA PORTABILIDAD DE LA LÍNEA TELEFÓNICA Y DURANTE 6 MESES, DE MANERA MENSUAL SE REALIZARÁ UNA BONIFICACIÓN DE $100 PESOS SOBRE LA RENTA MENSUAL DEL PAQUETE CONTRATADO. AL CONTRATAR UN PLAN TOTALPLAY INTERNET Y PORTAR LA LÍNEA TELEFÓNICA A TOTALPLAY. A PARTIR DE QUE SE REALICE LA PORTABILIDAD DE LA LÍNEA TELEFÓNICA Y DURANTE 6 MESES, DE MANERA MENSUAL SE REALIZARÁ UNA BONIFICACIÓN DE $50 PESOS SOBRE LA RENTA MENSUAL DEL PAQUETE CONTRATADO. NO APLICA A SERVICIOS ADICIONALES CONTRATADOS. NO ES ACUMULABLE CON OTRAS PROMOCIONES.
        </p>

        <h4>
        PROMOCIÓN HBO POR 2 MESES
        </h4>

        <p>
        TOTAL PLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. PROMOCIONES VÁLIDAS DEL 1 AL 31 DE MARZO DEL 2021 AL CONTRATAR EL PAQUETE DE HBO EL CLIENTE OBTENDRÁ DURANTE 2 MESES EL PAQUETE HBO, AL TERMINAR LOS MESES DE PROMOCIÓN DEBERÁ PAGAR EL PAQUETE A PRECIO DE LISTA. APLICA PARA CLIENTES NUEVOS EN PLANES CON SERVICIO DE TV EN LAS ZONAS CON COBERTURA TOTALPLAY.
        </p>

        <h4>
        PROMOCIÓN STAR PREMIUM A PRECIO ESPECIAL
        </h4>
        <p>
        TOTAL PLAY TELECOMUNICACIONES S.A. DE C.V. TODOS LOS DERECHOS RESERVADOS. TARIFAS REGISTRADAS ANTE IFT. REGISTRO DE LAS PROMOCIONES PRESENTADO ANTE IFT. PRECIOS INCLUYEN IMPUESTOS APLICABLES. PROMOCIONES VÁLIDAS DEL 1 AL 31 DE MARZO DEL 2021 AL CONTRATAR STAR PREMIUM EL CLIENTE OBTENDRÁ PRECIO ESPECIAL DURANTE 6 MESES; PAGANDO $139 PESOS MENSUALES. AL TERMINAR LOS MESES DE PROMOCIÓN DEBERÁ PAGAR EL PAQUETE A PRECIO DE LISTA. APLICA PARA CLIENTES NUEVOS EN PLANES CON SERVICIO DE TV EN LAS ZONAS CON COBERTURA TOTALPLAY.
        </p>
        </div>

        <div class="col-md-12">
<h4>
Política de privacidad
</h4>

<p>

</p>
Total Play Telecomunicaciones, S.A. de C.V., en adelante “TOTALPLAY”, con domicilio en Periférico Sur 4119, Torre A, Piso 7, Colonia Fuentes del Pedregal, C.P. 14140, Ciudad de México, en cumplimiento a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, su reglamento y los lineamientos y estándares nacionales e internacionales en materia de Protección de Datos Personales, asimismo, en estricto apego al cumplimento de los principios establecidos en la Ley y los deberes de seguridad y confidencialidad, aplica las medidas de seguridad físicas, administrativas y tecnológicas pertinentes durante todo el tratamiento y ciclo de vida de sus datos personales, en términos del presente Aviso de Privacidad:

1. Datos Personales que solicita de sus clientes:

A efecto de llevar la prestación de nuestros servicios, ofrecerle nuevas soluciones de entretenimiento, recibir sus comentarios e inquietudes, y brindarle el servicio de calidad que usted merece, le solicitaremos los siguientes datos personales:

Con fines prospección comercial, de identificación y autenticación para la contratación:

Nombre completo (Primer y segundo nombre, en caso de aplicar; y apellidos). Domicilio completo, incluyendo calle, número, colonia, código postal, municipio o delegación, Estado y País; así como referencias de localización para la correcta ubicación de su domicilio y poderle informar de la cobertura de nuestros servicios y en su caso la instalación de los equipos. Teléfono celular. Teléfono de casa. Teléfono de oficina. Correo electrónico. Es probable que le solicitemos en algún momento del proceso de contratación una identificación oficial

Voz Conservación y almacenamiento de los contratos y mensajes de datos. Esta información también puede ser requerida para el servicio técnico y seguimiento a quejas, instalaciones o actualizaciones al contrato o notificarle la ampliación de nuestra cobertura de servicio.

2. Datos financieros:

“TOTALPLAY”, a efecto de procesar sus pagos, generar y enviar sus facturas, solicita los siguientes datos financieros:

Nombre o razón social del cliente RFC Domicilio Fiscal Nombre del titular de la tarjeta de crédito Tipo de tarjeta de crédito (VISA, MASTERCARD, AMERICAN EXPRESS) Número de tarjeta CVV Fecha de expiración Domicilio del tarjetahabiente si es distinto a quien está efectuando la compra Correo electrónico

3. Finalidades de Tratamiento:

A continuación, se citan las finalidades para las cuales efectuamos tratamiento de sus datos personales:

PRIMARIAS

Contacto Contratación y prestación de nuestros servicios. Información y asesoría respecto de la cobertura de nuestros servicios y la oferta de los mismos. Atención a clientes Seguimiento a quejas Soporte técnico

SECUNDARIAS

Envío de publicidad e información relativa a promociones, mejoras y nuevos servicios

Estadística y segmentación de mercado

4. En “TOTALPLAY”, no solicitamos datos sensibles; sin embargo, con motivo de la prestación de nuestros servicios existe información que pudiese encuadrar en esta clasificación, la cual, en cumplimiento de los principios de la Ley así como de los deberes de seguridad y confidencialidad, se encuentran debidamente resguardados.

5. Transferencias:

“TOTALPLAY”, no realiza transferencias de datos a terceros, salvo aquellas excepciones contempladas en la Ley, incluyendo aquellas que, por Ley, mandamiento de autoridad competente o que por motivo del contrato de prestación de servicios resulten indispensables para la correcta ejecución del mismo.

6. Medios y/o procedimiento para el ejercicio de Derechos ARCO:

Usted podrá limitar u oponerse al tratamiento de sus datos, el uso o divulgación de los mismos o bien revocar su consentimiento, de manera personal directamente en nuestro Departamento de Protección de Datos Personales, ubicado en Av. Eje Central Lázaro Cárdenas, número 911, piso 4, 5 y 6, Colonia Vértiz Narvarte, C.P. 03800, Ciudad de México, o a través del correo electrónico: protecciondedatos@totalplay.com.mx

Para el ejercicio de sus derechos de Acceso, Rectificación, Cancelación y Oposición, podrá acudir de manera personal directamente a nuestro Departamento de Protección de Datos Personales, ubicado en Av. Eje Central Lázaro Cárdenas, número 911, piso 4, 5 y 6, Colonia Vértiz Narvarte, C.P. 03800, Ciudad de México, o podrá enviar su solicitud al correo electrónico: protecciondedatos@totalplay.com.mx

Su solicitud de derechos ARCO deberá contener:

Nombre completo

Copia simple o copia digital de identificación oficial para acreditar la identidad. (IFE, pasaporte, cédula profesional).

Representación: En caso de actuar en representación de un menor, se deberá presentar acta de nacimiento o documento oficial donde se acredite la personalidad del padre o tutor; en caso de actuar en representación de un tercero mayor de edad, deberá adjuntar el poder donde se acrediten sus facultades para actuar en representación del mismo.

Descripción breve de lo que solicita, ya sea el acceso a sus datos, rectificación o cancelación de los mismos, oposición al tratamiento o algunas finalidades del tratamiento o revocación del consentimiento.

Para rectificar su nombre, anexar copia de justificativo en caso de ser distinto a la identificación oficial presentada para acreditar la identidad.

El plazo de respuesta será de 20 días hábiles con base en el calendario oficial publicado en el Diario Oficial de la Federación.

La respuesta a su solicitud será enviada a través del medio que usted nos indique.

En caso de no recibir respuesta o no ser satisfactoria usted puede acudir al INAI, dentro de los 15 días hábiles posteriores a la recepción o ausencia de la misma.

7. Cambios al Aviso de Privacidad:

Los cambios a este aviso de privacidad le serán notificados vía correo electrónico o a través de este sitio web.

8. Cookies o Web Beacons

Para mejorar la experiencia del usuario y poder hacer más eficiente nuestro servicio, podemos utilizar cualquiera de estas herramientas tecnológicas con fines estadísticos y de geolocalización, sin embargo, estas pueden ser deshabilitadas por el usuario en caso de no desear que se encuentren activas.
        </div>























        <!-- <el-tabs v-model="activeName">
            <el-tab-pane label="Términos y Condiciones Naional" name="first" class="animated fadeIn">
                <national-component ></national-component>
            </el-tab-pane>
            <el-tab-pane label="Términos y condiciones Frontera" name="second" class="animated fadeIn">
                <frontier-component ></frontier-component>
            </el-tab-pane>
        </el-tabs> -->
    </div>
</div>
</template>

<script>
import national from './National';
import frontier from './Frontier';
export default {
    components:{
        'national-component': national,
        'frontier-component': frontier
    },
    data(){
        return {
            activeName: 'first'
        }
    },
    mounted() {
        setTimeout(() => {
            this.$store._modules.root.state.totalplay.loading = false;
        }, 1000);
    },
}
</script>
